baseurl: /cs476
# baseurl: /cs476-2020-spring
livereload: true
# profile: true

# Conversion markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

#markdown: kramdown # use <TAG markdown="1"> to render markdown within HTML tags!
#highlighter: none
#markdown: kramdown
#kramdown:
#   syntax_highlighter_opts:
#      disable : true

mathjax: true
defaults:
    - scope:
        path: "code"
      values:
        code: true
