###
### Website Settings
### => NOTE: Access variables here with: site.data.settings.XXXXXXXXX
###
siteauthor: '[Travis Peters](https://www.traviswpeters.com/)'

# Instructor-specific variables
school: 'Montana State University'
instructor: '<i class="fas fa-user-circle"></i> [Travis Peters](https://www.traviswpeters.com/)'
img: 'assets/me.png'
office: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342"><i class="fas fa-map-pin"></i> NAH 253A</a>'
officephone: '<a target="_blank" href="tel:4069944296‬"><i class="fas fa-phone"></i> 406-994-**4296‬**</a>'
email: '<i class="fas fa-envelope"></i> [travis.peters1@montana.edu](mailto:travis.peters1@montana.edu?subject=CS 476 Help)'

# Course-specific variables
title: 'Computer Security'
titlenum: 'CS 476'
term: 'Spring 2020'
dates: 'Jan 13, 2020 - May 08, 2020'
lectures: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342"><i class="fas fa-map-pin"></i> Norm Asbjornson Hall (NAH) 137</a> | Tuesday/Thursday 3:05 pm &ndash; 4:20 pm'
officehours: "Tuesday/Thursday 4:30 pm &ndash; 6:00 pm and by appointment."
textbook: "[Computer & Internet Security: A Hands-on Approach (2nd Edition)](https://www.handsonsecurity.net), by Wenliang Du"
finalexamdate: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342"><i class="fas fa-map-pin"></i> Norm Asbjornson Hall (NAH) 137</a> - May 8, 2020 (2:00 &ndash; 3:50 pm)'

# --> baseurl set in _config.yml
homeurl: https://traviswpeters.github.io/
url: https://traviswpeters.github.io/cs476/
githuburl: https://github.com/traviswpeters/cs476

# COURSE LINKS
questionnaire: '<i class="fas fa-external-link-alt"></i> [Questionnaire](https://forms.gle/bEMav7XE9h5Nuybg7)'
d2l: '<i class="fas fa-external-link-alt"></i> [D2L](https://ecat.montana.edu/d2l/home/576326)'
campuswire: '<i class="fas fa-external-link-alt"></i> [Campuswire](https://campuswire.com/p/GFCEDCB39)'
campuswirecode: 'Class Join Code: 6671'
slack: '<i class="fas fa-external-link-alt"></i> [Slack (CSCI 476 - Spring 2020)](https://csci476-sp2020.slack.com)'
slackjoin: '<i class="fas fa-external-link-alt"></i> [Slack (CSCI 476 - Spring 2020)](https://join.slack.com/t/csci476-sp2020/shared_invite/enQtODgyOTc3NDk2NTEzLTg2NmU0M2ZhMDJhODlkYjJkZTY3NjkyMjVmZmNhZGVkMDc1MDY1ZjY2OWM2NTE3YWJjZDk0MWI1MjdkNGM4OGQ)'
piazza: '<i class="fas fa-external-link-alt"></i> [Piazza](https://piazza.com/class/k4xcvl4uuv42f2?cid=4#)'
gradescope: '<i class="fas fa-external-link-alt"></i> [Gradescope](https://www.gradescope.com/courses/78110)'
ssc: '<i class="fas fa-external-link-alt"></i> [Student Success Center](https://www.cs.montana.edu/student-success-center.html)'

# SEED LINKS
seedlabs: 'https://seedsecuritylabs.org/Labs_16.04/'
# seedcode: 'https://github.com/traviswpeters/csci476-code' # my fork
seedcode: '<i class="fas fa-external-link-alt"></i> [CSCI 476 Code](https://github.com/traviswpeters/csci476-code)'

# locations of things (notes, slides, etc.)
slides: "files"
notes: "files"
code: "code"
reading: "files"
solutions: "files"

menu:
# - {name: 'Syllabus', url: ''}
- {name: '<span class="text-success">COVID-19 Info <i>(New!)</i></span>', url: 'covid19'}
- {name: 'Logistics', url: '#logistics'}
- {name: 'Schedule', url: '#schedule'}
- {name: 'Labs', url: 'labs'}
- {name: 'Resources', url: 'resources'}
# - {name: 'Exams', url: '#exams'}
# - {name: 'Code', url: 'https://github.com/traviswpeters/csci476-code'}

exams:
  files: "files"
  finalexam:
    name: 'Final Exam'
    date: 'XX/XX/2020'
    url: '#exams'
    show: False # show on schedule?
