###
### Website Settings
###

# NOTE: Access variables here with: site.data.settings.XXXXXXXXX

# Instructor-specific variables
school: 'Montana State University'
instructor: '<i class="fas fa-user-circle"></i> [Travis Peters](https://www.traviswpeters.com/)'
img: 'assets/me.png'
office: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342"><i class="fas fa-map-pin"></i> NAH 253A</a>'
officephone: '<i class="fas fa-phone"></i>‭ 406-994-**4296‬**'
officephoneext: "x4296" # extension
email: '<i class="fas fa-envelope"></i> [travis.peters1@montana.edu](mailto:travis.peters1@montana.edu?subject=CS 476 Help)'

# Course-specific variables
title: 'Computer Security'
titlenum: 'CS 476'
term: 'Spring 2020'
dates: 'Jan 13, 2020 - May 08, 2020'
lectures: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=9"><i class="fas fa-map-pin"></i> Reid Hall 103</a> | Tuesday/Thursday 3:05 pm &ndash; 4:20 pm'
officehours: "Tuesday/Thursday 4:30 pm &ndash; 6:00 pm and by appointment."
textbook: "[Computer & Internet Security: A Hands-on Approach (2nd Edition)](https://www.handsonsecurity.net), by Wenliang Du"

# --> baseurl set in _config.yml
homeurl: https://traviswpeters.github.io/
url: https://traviswpeters.github.io/cs476/
githuburl: https://github.com/traviswpeters/cs476

# COURSE LINKS
d2l: '<i class="fas fa-external-link-alt"></i> [D2L](https://ecat.montana.edu/d2l/home/553509)'
gradescope: '<i class="fas fa-external-link-alt"></i> [Gradescope](https://www.gradescope.com/)'
ssc: '<i class="fas fa-external-link-alt"></i> [Student Success Center](https://www.cs.montana.edu/student-success-center.html)'
questionnaire: '<i class="fas fa-external-link-alt"></i> [Questionnaire](https://forms.gle/Krmco3bNsbPRjSca7)'

# locations of things (notes, slides, etc.)
slides: "notes"
notes: "notes"
solutions: "solutions"
code: "code"
reading: "notes"
projectfiles: 'project'

menu:
# - {name: 'Syllabus', url: ''}
# - {name: 'Logistics', url: '#logistics'}
# - {name: 'Resources', url: '#resources'}
# - {name: 'Schedule', url: '#schedule'}
# - {name: 'Exams', url: '#exams'}
# - {name: 'Assignments', url: '#assignments'}
# - {name: 'Project', url: '#project'}
# - {name: 'Extra Credit', url: 'xc'}
# - {name: 'Code', url: 'code'}

assignments:
  a0:
    shortname: 'A0'
    longname: 'Assignment 0: Questionnaire & VM Setup'
    url: 'a0'
    # due: 'Due 01/30'
    # timedue: '@10pm'
    # duecheckpoint: 'Friday, October 4th, 2019 @10pm'
    # duelong: 'Wednesday, October 16th, 2019 @10pm'
    show: False # show on schedule?

exams:
  files: "notes"
  exam1:
    name: 'Exam 1'
    date: 'XX/XX/2020'
    url: '#exams'
    show: False # show on schedule?
  exam1:
    name: 'Exam 2'
    date: 'XX/XX/2020'
    url: '#exams'
    show: False # show on schedule?
