# A super simple Makefile for buidling the probe program from class.
#
# You should remove the .txt extension for this file (that is just for friendly viewing in the browswer).
#
# A good Makefile reference: http://www.csheeet.com/en/latest/notes/c_make.html

CC = gcc
CFLAGS = -Wall -std=c99 -ggdb
EXECS = probe

.PHONY: all clean

all: probe 

# targets
probe: probe.c
	$(CC) $(CFLAGS) probe.c -o $@

clean:
	rm -f $(EXECS)
	rm -rf *.dSYM/
